[discord]
# 大獎、看門狗重啟、水道異常告警頻道
alert_webhook = https://discord.com/api/webhooks/1501109892398841947/PCtI4v9T4e4m6-N8qx5WVcdkIv9bjd8lR2V6dzlseSjPfNCz8oK2Xfui4jxFRcJRaIDC
# 每 30 分鐘收益與日預估報表頻道
report_webhook = https://discord.com/api/webhooks/1501110159152381952/vXBjM02T6PmiJ6lDCcMUFmS50Vd5yjoICy5hxINVPDvTMZbckOwTBYoqCI3MXH1lU-RD

[custom_stats]
# 格式：英文原名 #中文標籤 (程式會自動偵測英文並顯示中文)
item1 = Seven Years Bad Luck #七年
item2 = The Apothecary #藥劑師
item3 = The Black Barya #黑幣

[settings]
# 是否關閉水道告警推播 (true: 不推播 / false: 滿5次即告警)
aqueduct_only = false
